#include <avr/io.h>
#include "digits.h"



#define BIT_SET(a,b) ((a) |= (1<<(b)))
#define BIT_CLE(a,b) ((a) &= ~(1<<(b)))
#define BIT_FLIP(a,b) ((a) ^= (1<<(b)))
#define BIT_CHECK(a,b) ((a) & (1<<(b)))

#define S1B_PIN PD1
#define S1C_PIN PD2
#define S1B_PORT PORTD
#define S1C_PORT PORTD

#define S2A_PIN PC2
#define S2B_PIN PC0
#define S2C_PIN PC1
#define S2D_PIN PC4
#define S2E_PIN PD0
#define S2F_PIN PC3
#define S2G_PIN PC5
#define S2A_PORT PORTC
#define S2B_PORT PORTC
#define S2C_PORT PORTC
#define S2D_PORT PORTC
#define S2E_PORT PORTD
#define S2F_PORT PORTC
#define S2G_PORT PORTC

#define S3A_PIN PB3
#define S3B_PIN PB2
#define S3C_PIN PB4
#define S3D_PIN PA0
#define S3E_PIN PA1
#define S3F_PIN PB5
#define S3G_PIN PC7
#define S3A_PORT PORTB
#define S3B_PORT PORTB
#define S3C_PORT PORTB
#define S3D_PORT PORTA
#define S3E_PORT PORTA
#define S3F_PORT PORTB
#define S3G_PORT PORTC

#define S4A_PIN PD5
#define S4B_PIN PB6
#define S4C_PIN PB7
#define S4D_PIN PD7
#define S4E_PIN PB1
#define S4F_PIN PD6
#define S4G_PIN PB0
#define S4A_PORT PORTD
#define S4B_PORT PORTB
#define S4C_PORT PORTB
#define S4D_PORT PORTD
#define S4E_PORT PORTB
#define S4F_PORT PORTD
#define S4G_PORT PORTB

void set_digit_4(uint8_t digit) {
switch (digit) {
        case 0: 
			BIT_CLE(S4A_PORT, S4A_PIN);
			BIT_CLE(S4B_PORT, S4B_PIN);
			BIT_CLE(S4C_PORT, S4C_PIN);
			BIT_CLE(S4D_PORT, S4D_PIN);
			BIT_CLE(S4E_PORT, S4E_PIN);
			BIT_CLE(S4F_PORT, S4F_PIN);
			BIT_SET(S4G_PORT, S4G_PIN);
		break;
        case 1:
			BIT_SET(S4A_PORT, S4A_PIN); 
			BIT_CLE(S4B_PORT, S4B_PIN);
			BIT_CLE(S4C_PORT, S4C_PIN);
			BIT_SET(S4D_PORT, S4D_PIN); 
			BIT_SET(S4E_PORT, S4E_PIN); 
			BIT_SET(S4F_PORT, S4F_PIN); 
			BIT_SET(S4G_PORT, S4G_PIN);
		break;
		case 2:
			BIT_CLE(S4A_PORT, S4A_PIN); 
			BIT_CLE(S4B_PORT, S4B_PIN);
			BIT_SET(S4C_PORT, S4C_PIN);
			BIT_CLE(S4D_PORT, S4D_PIN); 
			BIT_CLE(S4E_PORT, S4E_PIN); 
			BIT_SET(S4F_PORT, S4F_PIN); 
			BIT_CLE(S4G_PORT, S4G_PIN);
			break;
		case 3:
			BIT_CLE(S4A_PORT, S4A_PIN); 
			BIT_CLE(S4B_PORT, S4B_PIN);
			BIT_CLE(S4C_PORT, S4C_PIN);
			BIT_CLE(S4D_PORT, S4D_PIN); 
			BIT_SET(S4E_PORT, S4E_PIN); 
			BIT_SET(S4F_PORT, S4F_PIN); 
			BIT_CLE(S4G_PORT, S4G_PIN);
		break;
		case 4:
			BIT_SET(S4A_PORT, S4A_PIN); 
			BIT_CLE(S4B_PORT, S4B_PIN);
			BIT_CLE(S4C_PORT, S4C_PIN);
			BIT_SET(S4D_PORT, S4D_PIN); 
			BIT_SET(S4E_PORT, S4E_PIN); 
			BIT_CLE(S4F_PORT, S4F_PIN); 
			BIT_CLE(S4G_PORT, S4G_PIN);
		break;
		case 5:
			BIT_CLE(S4A_PORT, S4A_PIN); 
			BIT_SET(S4B_PORT, S4B_PIN);
			BIT_CLE(S4C_PORT, S4C_PIN);
			BIT_CLE(S4D_PORT, S4D_PIN); 
			BIT_SET(S4E_PORT, S4E_PIN); 
			BIT_CLE(S4F_PORT, S4F_PIN); 
			BIT_CLE(S4G_PORT, S4G_PIN);
		break;
		case 6:
			BIT_CLE(S4A_PORT, S4A_PIN); 
			BIT_SET(S4B_PORT, S4B_PIN);
			BIT_CLE(S4C_PORT, S4C_PIN);
			BIT_CLE(S4D_PORT, S4D_PIN); 
			BIT_CLE(S4E_PORT, S4E_PIN); 
			BIT_CLE(S4F_PORT, S4F_PIN); 
			BIT_CLE(S4G_PORT, S4G_PIN);
		break;
		case 7:
			BIT_CLE(S4A_PORT, S4A_PIN); 
			BIT_CLE(S4B_PORT, S4B_PIN);
			BIT_CLE(S4C_PORT, S4C_PIN);
			BIT_SET(S4D_PORT, S4D_PIN); 
			BIT_SET(S4E_PORT, S4E_PIN); 
			BIT_SET(S4F_PORT, S4F_PIN); 
			BIT_SET(S4G_PORT, S4G_PIN);
		break;
		case 8:
			BIT_CLE(S4A_PORT, S4A_PIN); 
			BIT_CLE(S4B_PORT, S4B_PIN);
			BIT_CLE(S4C_PORT, S4C_PIN);
			BIT_CLE(S4D_PORT, S4D_PIN); 
			BIT_CLE(S4E_PORT, S4E_PIN); 
			BIT_CLE(S4F_PORT, S4F_PIN); 
			BIT_CLE(S4G_PORT, S4G_PIN);
		break;
		case 9:
			BIT_CLE(S4A_PORT, S4A_PIN); 
			BIT_CLE(S4B_PORT, S4B_PIN);
			BIT_CLE(S4C_PORT, S4C_PIN);
			BIT_CLE(S4D_PORT, S4D_PIN); 
			BIT_SET(S4E_PORT, S4E_PIN); 
			BIT_CLE(S4F_PORT, S4F_PIN); 
			BIT_CLE(S4G_PORT, S4G_PIN);
		break;
		default: // print E error
			BIT_CLE(S4A_PORT, S4A_PIN); 
			BIT_SET(S4B_PORT, S4B_PIN);
			BIT_SET(S4C_PORT, S4C_PIN);
			BIT_CLE(S4D_PORT, S4D_PIN); 
			BIT_CLE(S4E_PORT, S4E_PIN); 
			BIT_CLE(S4F_PORT, S4F_PIN); 
			BIT_CLE(S4G_PORT, S4G_PIN);
    }
}

void set_digit_3(uint8_t digit) {
switch (digit) {
        case 0: 
			BIT_CLE(S3A_PORT, S3A_PIN);
			BIT_CLE(S3B_PORT, S3B_PIN);
			BIT_CLE(S3C_PORT, S3C_PIN);
			BIT_CLE(S3D_PORT, S3D_PIN);
			BIT_CLE(S3E_PORT, S3E_PIN);
			BIT_CLE(S3F_PORT, S3F_PIN);
			BIT_SET(S3G_PORT, S3G_PIN);
		break;
        case 1:
			BIT_SET(S3A_PORT, S3A_PIN); 
			BIT_CLE(S3B_PORT, S3B_PIN);
			BIT_CLE(S3C_PORT, S3C_PIN);
			BIT_SET(S3D_PORT, S3D_PIN); 
			BIT_SET(S3E_PORT, S3E_PIN); 
			BIT_SET(S3F_PORT, S3F_PIN); 
			BIT_SET(S3G_PORT, S3G_PIN);
		break;
		case 2:
			BIT_CLE(S3A_PORT, S3A_PIN); 
			BIT_CLE(S3B_PORT, S3B_PIN);
			BIT_SET(S3C_PORT, S3C_PIN);
			BIT_CLE(S3D_PORT, S3D_PIN); 
			BIT_CLE(S3E_PORT, S3E_PIN); 
			BIT_SET(S3F_PORT, S3F_PIN); 
			BIT_CLE(S3G_PORT, S3G_PIN);
		break;
		case 3:
			BIT_CLE(S3A_PORT, S3A_PIN); 
			BIT_CLE(S3B_PORT, S3B_PIN);
			BIT_CLE(S3C_PORT, S3C_PIN);
			BIT_CLE(S3D_PORT, S3D_PIN); 
			BIT_SET(S3E_PORT, S3E_PIN); 
			BIT_SET(S3F_PORT, S3F_PIN); 
			BIT_CLE(S3G_PORT, S3G_PIN);
		break;
		case 4:
			BIT_SET(S3A_PORT, S3A_PIN); 
			BIT_CLE(S3B_PORT, S3B_PIN);
			BIT_CLE(S3C_PORT, S3C_PIN);
			BIT_SET(S3D_PORT, S3D_PIN); 
			BIT_SET(S3E_PORT, S3E_PIN); 
			BIT_CLE(S3F_PORT, S3F_PIN); 
			BIT_CLE(S3G_PORT, S3G_PIN);
		break;
		case 5:
			BIT_CLE(S3A_PORT, S3A_PIN); 
			BIT_SET(S3B_PORT, S3B_PIN);
			BIT_CLE(S3C_PORT, S3C_PIN);
			BIT_CLE(S3D_PORT, S3D_PIN); 
			BIT_SET(S3E_PORT, S3E_PIN); 
			BIT_CLE(S3F_PORT, S3F_PIN); 
			BIT_CLE(S3G_PORT, S3G_PIN);
		break;
		case 6:
			BIT_CLE(S3A_PORT, S3A_PIN); 
			BIT_SET(S3B_PORT, S3B_PIN);
			BIT_CLE(S3C_PORT, S3C_PIN);
			BIT_CLE(S3D_PORT, S3D_PIN); 
			BIT_CLE(S3E_PORT, S3E_PIN); 
			BIT_CLE(S3F_PORT, S3F_PIN); 
			BIT_CLE(S3G_PORT, S3G_PIN);
		break;
		case 7:
			BIT_CLE(S3A_PORT, S3A_PIN); 
			BIT_CLE(S3B_PORT, S3B_PIN);
			BIT_CLE(S3C_PORT, S3C_PIN);
			BIT_SET(S3D_PORT, S3D_PIN); 
			BIT_SET(S3E_PORT, S3E_PIN); 
			BIT_SET(S3F_PORT, S3F_PIN); 
			BIT_SET(S3G_PORT, S3G_PIN);
		break;
		case 8:
			BIT_CLE(S3A_PORT, S3A_PIN); 
			BIT_CLE(S3B_PORT, S3B_PIN);
			BIT_CLE(S3C_PORT, S3C_PIN);
			BIT_CLE(S3D_PORT, S3D_PIN); 
			BIT_CLE(S3E_PORT, S3E_PIN); 
			BIT_CLE(S3F_PORT, S3F_PIN); 
			BIT_CLE(S3G_PORT, S3G_PIN);
		break;
		case 9:
			BIT_CLE(S3A_PORT, S3A_PIN); 
			BIT_CLE(S3B_PORT, S3B_PIN);
			BIT_CLE(S3C_PORT, S3C_PIN);
			BIT_CLE(S3D_PORT, S3D_PIN); 
			BIT_SET(S3E_PORT, S3E_PIN); 
			BIT_CLE(S3F_PORT, S3F_PIN); 
			BIT_CLE(S3G_PORT, S3G_PIN);
		break;
		default: // print E error
			BIT_CLE(S3A_PORT, S3A_PIN); 
			BIT_SET(S3B_PORT, S3B_PIN);
			BIT_SET(S3C_PORT, S3C_PIN);
			BIT_CLE(S3D_PORT, S3D_PIN); 
			BIT_CLE(S3E_PORT, S3E_PIN); 
			BIT_CLE(S3F_PORT, S3F_PIN); 
			BIT_CLE(S3G_PORT, S3G_PIN);
    }
}

void set_digit_2(uint8_t digit) {
switch (digit) {
        case 0: 
			BIT_CLE(S3A_PORT, S2A_PIN);
			BIT_CLE(S2B_PORT, S2B_PIN);
			BIT_CLE(S2C_PORT, S2C_PIN);
			BIT_CLE(S2D_PORT, S2D_PIN);
			BIT_CLE(S2E_PORT, S2E_PIN);
			BIT_CLE(S2F_PORT, S2F_PIN);
			BIT_SET(S2G_PORT, S2G_PIN);
		break;
        case 1:
			BIT_SET(S2A_PORT, S2A_PIN); 
			BIT_CLE(S2B_PORT, S2B_PIN);
			BIT_CLE(S2C_PORT, S2C_PIN);
			BIT_SET(S2D_PORT, S2D_PIN); 
			BIT_SET(S2E_PORT, S2E_PIN); 
			BIT_SET(S2F_PORT, S2F_PIN); 
			BIT_SET(S2G_PORT, S2G_PIN);
		break;
		case 2:
			BIT_CLE(S2A_PORT, S2A_PIN); 
			BIT_CLE(S2B_PORT, S2B_PIN);
			BIT_SET(S2C_PORT, S2C_PIN);
			BIT_CLE(S2D_PORT, S2D_PIN); 
			BIT_CLE(S2E_PORT, S2E_PIN); 
			BIT_SET(S2F_PORT, S2F_PIN); 
			BIT_CLE(S2G_PORT, S2G_PIN);
		break;
		case 3:
			BIT_CLE(S2A_PORT, S2A_PIN); 
			BIT_CLE(S2B_PORT, S2B_PIN);
			BIT_CLE(S2C_PORT, S2C_PIN);
			BIT_CLE(S2D_PORT, S2D_PIN); 
			BIT_SET(S2E_PORT, S2E_PIN); 
			BIT_SET(S2F_PORT, S2F_PIN); 
			BIT_CLE(S2G_PORT, S2G_PIN);
		break;
		case 4:
			BIT_SET(S2A_PORT, S2A_PIN); 
			BIT_CLE(S2B_PORT, S2B_PIN);
			BIT_CLE(S2C_PORT, S2C_PIN);
			BIT_SET(S2D_PORT, S2D_PIN); 
			BIT_SET(S2E_PORT, S2E_PIN); 
			BIT_CLE(S2F_PORT, S2F_PIN); 
			BIT_CLE(S2G_PORT, S2G_PIN);
		break;
		case 5:
			BIT_CLE(S2A_PORT, S2A_PIN); 
			BIT_SET(S2B_PORT, S2B_PIN);
			BIT_CLE(S2C_PORT, S2C_PIN);
			BIT_CLE(S2D_PORT, S2D_PIN); 
			BIT_SET(S2E_PORT, S2E_PIN); 
			BIT_CLE(S2F_PORT, S2F_PIN); 
			BIT_CLE(S2G_PORT, S2G_PIN);
		break;
		case 6:
			BIT_CLE(S2A_PORT, S2A_PIN); 
			BIT_SET(S2B_PORT, S2B_PIN);
			BIT_CLE(S2C_PORT, S2C_PIN);
			BIT_CLE(S2D_PORT, S2D_PIN); 
			BIT_CLE(S2E_PORT, S2E_PIN); 
			BIT_CLE(S2F_PORT, S2F_PIN); 
			BIT_CLE(S2G_PORT, S2G_PIN);
		break;
		case 7:
			BIT_CLE(S2A_PORT, S2A_PIN); 
			BIT_CLE(S2B_PORT, S2B_PIN);
			BIT_CLE(S2C_PORT, S2C_PIN);
			BIT_SET(S2D_PORT, S2D_PIN); 
			BIT_SET(S2E_PORT, S2E_PIN); 
			BIT_SET(S2F_PORT, S2F_PIN); 
			BIT_SET(S2G_PORT, S2G_PIN);
		break;
		case 8:
			BIT_CLE(S2A_PORT, S2A_PIN); 
			BIT_CLE(S2B_PORT, S2B_PIN);
			BIT_CLE(S2C_PORT, S2C_PIN);
			BIT_CLE(S2D_PORT, S2D_PIN); 
			BIT_CLE(S2E_PORT, S2E_PIN); 
			BIT_CLE(S2F_PORT, S2F_PIN); 
			BIT_CLE(S2G_PORT, S2G_PIN);
		break;
		case 9:
			BIT_CLE(S2A_PORT, S2A_PIN); 
			BIT_CLE(S2B_PORT, S2B_PIN);
			BIT_CLE(S2C_PORT, S2C_PIN);
			BIT_CLE(S2D_PORT, S2D_PIN); 
			BIT_SET(S2E_PORT, S2E_PIN); 
			BIT_CLE(S2F_PORT, S2F_PIN); 
			BIT_CLE(S2G_PORT, S2G_PIN);
		break;
		default: // print E error
			BIT_CLE(S2A_PORT, S2A_PIN); 
			BIT_SET(S2B_PORT, S2B_PIN);
			BIT_SET(S2C_PORT, S2C_PIN);
			BIT_CLE(S2D_PORT, S2D_PIN); 
			BIT_CLE(S2E_PORT, S2E_PIN); 
			BIT_CLE(S2F_PORT, S2F_PIN); 
			BIT_CLE(S2G_PORT, S2G_PIN);
    }
}

void set_digit_1(uint8_t digit) {
if(digit == 1) {
	BIT_CLE(PORTD, PD1);
	BIT_CLE(PORTD, PD2);
} else { // disable
	BIT_SET(PORTD, PD1);
	BIT_SET(PORTD, PD2);
	}
}

/*
	set_all_digits parses two bytes of data returned by ds3231 from minutes and hours registers 
	and set digits accordingly
*/
void set_all_digits(uint16_t mmhh) {
	set_digit_1((mmhh&0x10)>>4); 
	set_digit_2(mmhh&0xF); 
	set_digit_3((mmhh>>12)&0x7); 
	set_digit_4((mmhh>>8)&0xF);
}